"""
AdaptiveAI — Recommendation Service
======================================
Manages AI stack recommendations generated by the multi-agent system.
"""

from datetime import datetime
from typing import Optional, Any

from app.storage.sheet_manager import get_sheet_manager
from app.schemas.recommendation import (
    RecommendationCreate, RecommendationInDB, RecommendationResponse,
)
from app.core.exceptions import RecordNotFoundError
from app.core.logging import get_logger

logger = get_logger("recommendation_service")


class RecommendationService:
    """Manages AI stack recommendations."""

    def __init__(self):
        self.sheets = get_sheet_manager()

    async def create(self, data: RecommendationCreate) -> RecommendationResponse:
        """Store a new recommendation, replacing the existing one if present."""
        existing = await self.sheets.recommendations.find_by_field("organization_id", data.organization_id)
        
        if existing:
            # We have an existing recommendation! Overwrite it in place.
            rec_id = existing[0].get("recommendation_id")
            update_data = {
                "recommended_tools": data.recommended_tools,
                "reasoning_summary": data.reasoning_summary,
                "workflow_alignment": data.workflow_alignment,
                "compatibility_score": data.compatibility_score,
                "roi_estimation": data.roi_estimation,
                "future_growth_prediction": data.future_growth_prediction,
                "created_at": datetime.utcnow().isoformat()
            }
            await self.sheets.recommendations.update(rec_id, update_data)
            
            # Re-read to construct response dict correctly
            merged = await self.sheets.recommendations.find_by_id(rec_id)
            logger.info(f"Replaced existing recommendation {rec_id} for org {data.organization_id}")
            return self._to_response(merged)
        else:
            # Create a brand new record
            rec = RecommendationInDB(**data.model_dump())
            await self.sheets.recommendations.insert(rec.model_dump())
            # Physically re-read the newly inserted recommendation from Excel sheet
            fetched = await self.sheets.recommendations.find_by_id(rec.recommendation_id)
            logger.info(f"Created brand new recommendation {rec.recommendation_id} for org {data.organization_id} and fetched back from Excel")
            return self._to_response(fetched or rec.model_dump())

    async def get_by_id(self, rec_id: str) -> RecommendationResponse:
        """Get recommendation by ID."""
        data = await self.sheets.recommendations.find_by_id(rec_id)
        if not data:
            raise RecordNotFoundError(f"Recommendation {rec_id} not found")
        return self._to_response(data)

    async def get_for_organization(self, org_id: str) -> list[RecommendationResponse]:
        """Get all recommendations for an organization."""
        records = await self.sheets.recommendations.find_by_field("organization_id", org_id)
        return [self._to_response(r) for r in records]

    async def get_latest_for_org(self, org_id: str) -> Optional[RecommendationResponse]:
        """Get the most recent recommendation for an organization."""
        records = await self.sheets.recommendations.find_all(
            filters={"organization_id": org_id},
            sort_by="created_at",
            sort_desc=True,
            limit=1,
        )
        if not records:
            return None
        return self._to_response(records[0])

    def _to_response(self, data: dict) -> RecommendationResponse:
        def safe_float(val: Any, default: float = 0.0) -> float:
            if val is None or val == "":
                return default
            try:
                return float(val)
            except (ValueError, TypeError):
                return default

        return RecommendationResponse(
            recommendation_id=data.get("recommendation_id", ""),
            organization_id=data.get("organization_id", ""),
            recommended_tools=str(data.get("recommended_tools", "")),
            reasoning_summary=str(data.get("reasoning_summary", "")),
            workflow_alignment=str(data.get("workflow_alignment", "")),
            compatibility_score=safe_float(data.get("compatibility_score"), 0.0),
            roi_estimation=str(data.get("roi_estimation", "")),
            future_growth_prediction=str(data.get("future_growth_prediction", "")),
            created_at=data.get("created_at", datetime.utcnow()),
        )
