"""
AdaptiveAI — Recommendation Schema
=====================================
Maps to RECOMMENDATIONS_MASTER.xlsx
Stores AI stack recommendations generated by multi-agent reasoning.
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field
import uuid


class RecommendationBase(BaseModel):
    organization_id: str
    recommended_tools: str = Field(default="", description="JSON string of recommended tool stack")
    reasoning_summary: str = Field(default="")
    workflow_alignment: str = Field(default="", description="How tools align with org workflows")
    compatibility_score: float = Field(default=0.0, ge=0.0, le=1.0)
    roi_estimation: str = Field(default="", description="JSON string of ROI analysis")
    future_growth_prediction: str = Field(default="", description="JSON string of growth predictions")


class RecommendationCreate(RecommendationBase):
    pass


class RecommendationInDB(RecommendationBase):
    recommendation_id: str = Field(default_factory=lambda: f"rec_{uuid.uuid4().hex[:12]}")
    created_at: datetime = Field(default_factory=datetime.utcnow)


class RecommendationResponse(BaseModel):
    recommendation_id: str
    organization_id: str
    recommended_tools: str
    reasoning_summary: str
    workflow_alignment: str
    compatibility_score: float
    roi_estimation: str
    future_growth_prediction: str
    created_at: datetime


class GenerateRecommendationRequest(BaseModel):
    """Request to generate a new AI stack recommendation."""
    organization_id: str
    focus_areas: Optional[str] = Field(default=None, description="Specific areas to focus on")
    budget_constraint: Optional[str] = Field(default=None, description="Budget limits")
    priority: Optional[str] = Field(default="balanced", description="balanced, cost, quality, speed")
